# Generated by Django 5.2.2 on 2026-07-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_message_options_rename_message_message_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
