# Generated by Django 5.2.2 on 2026-07-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_message_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('❤️', 'Heart'), ('😂', 'Laugh'), ('🔥', 'Fire'), ('😍', 'Love'), ('😮', 'Wow'), ('😢', 'Sad'), ('👍', 'Like'), ('👎', 'Dislike')], default='👍', max_length=8)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='network.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'user'], name='network_rea_message_876e44_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
