# Generated by Django 5.2.2 on 2026-07-10 15:22

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=network.models.chat_file_path),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.chat_image_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
