# Generated by Django 5.2.2 on 2026-07-24 16:31

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_message_is_pinned_message_pinned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=network.models.chat_video_path),
        ),
    ]
