# Generated by Django 5.2.2 on 2026-07-24 16:52

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=network.models.chat_audio_path),
        ),
    ]
