# Generated by Django 5.2.2 on 2026-07-24 17:24

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_message_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.poll_image_path),
        ),
        migrations.AddField(
            model_name='polloption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.poll_image_path),
        ),
    ]
