# Generated by Django 5.2.2 on 2026-06-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userprofile_otp_created_at_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
