# Generated by Django 5.2.2 on 2026-07-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_deliveryprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
