# Generated by Django 5.2.2 on 2026-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_banner_video_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.CharField(choices=[('food', 'Food Vendor'), ('printout', 'Printout Vendor')], default='food', max_length=20),
        ),
    ]
