# Generated by Django 5.2.2 on 2026-07-17 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_vendorprofile_vendor_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='print_orders/%Y/%m/')),
                ('pages', models.PositiveIntegerField()),
                ('copies', models.PositiveIntegerField(default=1)),
                ('print_type', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color Print')], default='bw', max_length=10)),
                ('paper_size', models.CharField(choices=[('a4', 'A4'), ('a3', 'A3')], default='a4', max_length=5)),
                ('binding', models.BooleanField(default=False)),
                ('lamination', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('printing', 'Printing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to='myapp.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
