# Generated by Django 5.2.2 on 2026-08-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_printorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='bw_price_per_page',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='color_price_per_page',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
