# Generated by Django 5.2.2 on 2026-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_vendorprofile_bw_price_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='bw_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printorder',
            name='color_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_type',
            field=models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color Print'), ('mixed', 'Mixed B&W + Color')], default='bw', max_length=10),
        ),
    ]
