# Generated by Django 5.2.2 on 2026-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_printorder_bw_pages_printorder_color_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(choices=[('single', 'One Side'), ('double', 'Double Side')], default='single', max_length=10),
        ),
    ]
