# Generated by Django 5.2.2 on 2026-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_printorder_print_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='bw_page_ranges',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='printorder',
            name='color_page_ranges',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
