# Generated by Django 5.2.2 on 2026-08-09 18:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_printorder_bw_page_ranges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='banners/videos/'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='document',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='print_orders/%Y/%m/'),
        ),
    ]
