# Generated by Django 5.2.2 on 2026-06-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
