# Generated by Django 5.2.2 on 2026-06-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_order_address_type_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CARD', 'Credit / Debit Card'), ('WALLET', 'Wallet')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
