# Generated by Django 5.2.2 on 2026-07-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_coupon_one_time_per_user_couponusage'),
        ('myapp', '0006_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='myapp.vendorprofile'),
        ),
    ]
